### ISSUE TITLE
tests fail in master and dev branches

### ISSUE THREAD

**Issue by santiaago** [taironas/route#17]
santiaago$ go test
    --- FAIL: TestServeStaticResources (0.00 seconds)
    	router_test.go:140: &{404 Not Found 404 HTTP/1.1 1 1 map[Content-Type:[text/plain; charset=utf-8] Date:[Wed, 21 Jan 2015 21:38:47 GMT] Content-Length:[19]] 0xc2100a0480 19 [] false map[] 0xc2100a1750}
    --- FAIL: TestServeTwoLevelStaticResources (0.00 seconds)
    	router_test.go:163: &{404 Not Found 404 HTTP/1.1 1 1 map[Content-Type:[text/plain; charset=utf-8] Date:[Wed, 21 Jan 2015 21:38:47 GMT] Content-Length:[19]] 0xc2100a0580 19 [] false map[] 0xc2100a1d00}
    FAIL
    exit status 1
    FAIL	github.com/taironas/route	0.019s

**Comment by rjourde** [comment]
Tests are in master. Could you re-test please and close the issue if everything is Ok?

**Comment by santiaago** [comment]
still failing, same error

**Comment by rjourde** [comment]
check again lol. You already encountered this situation. Check if you have
a folder named "temp_TestServeStaticResources" under C:\temp and delete it.

**Comment by santiaago** [comment]
I dont have a c:\temp folder I am in a mac

**Comment by rjourde** [comment]
not my f*ing problem :). test are only for windows. Windows is god...

**Comment by rjourde** [comment]
Tests passed on OS X and Windows. So close the issue.
