### ISSUE TITLE
add new test to have 100% coverage

### ISSUE THREAD

**Issue by rjourde** [taironas/route#21]
go test -coverprofile=coverage ..\route
go tool cover -html=coverage

**Comment by santiaago** [comment]
you can also do `go test -coverprofile=coverage` without the **..\route**

**Comment by rjourde** [comment]
![image](https://cloud.githubusercontent.com/assets/1008617/6189365/4c10fcea-b39a-11e4-99de-af9884c88202.png)
![image](https://cloud.githubusercontent.com/assets/1008617/6189371/568e52c6-b39a-11e4-998a-7ca3efb666d6.png)
