### ISSUE TITLE
Handle variables in URL path

### ISSUE THREAD

**Issue by santiaago** [taironas/route#7]
A variable starts with a semi colon and ends at the first slash:
`/url/:id`
`/url/:id/examples`
`/url/:id/examples/:exampleNumber`

Trailing slash will not be taken into account. `/url/:id/examples/` equivalent to `/url/:id/examples`

**Comment by rjourde** [comment]
Do you want to keep regexp matching ?
Better to bracket the variable instead of semi-colon ?

example: /users/[0-9]+/friends/{username}/?

**Comment by santiaago** [comment]
I prefer semi colon `:id`

**Comment by santiaago** [comment]
I think that would remove regexp matching right?

**Comment by rjourde** [comment]
ok for semi colon. so we match from ':' to first encountered '/'.
regarding regexp matching, for example, user might want to use it but he doesn't care about retrieving the permalink. I have no problem if you want to remove the regexp matching

**Comment by santiaago** [comment]
well I dont know what we should do:

we would like something like this:

`/url/:id`
`/url/:id/examples`
`/url/:id/examples/:exampleNumber`

but I also like that the regex let you handle the trailing `/` with the `/?` expression:

`/url/:id/?`
`/url/:id/examples/?`
`/url/:id/examples/:exampleNumber/?`

**Comment by rjourde** [comment]
yes yes

**Comment by rjourde** [comment]
we can keep the regexp matching but we don't handle the permalink, it is
just for the routing.

**Comment by santiaago** [comment]
what do you understand by **but we don't handle the permalink, it is
just for the routing**

**Comment by rjourde** [comment]
we keep the regexp matching so for instance if we have this route: r.
HandleFunc("/users/[0-9]+/?", userHandler), when localhost:8080/users/785
is accessed, the userHandler will be reached but we will not be able to
retrieve 785.

**Comment by santiaago** [comment]
I dont think that is usefull, I think we want to be able to access `:id` easily and handle trailing slashed as well.

**Comment by rjourde** [comment]
Ok i'm ok with that

**Comment by santiaago** [comment]
may should automatically handle trailing slashed:

So you only write:

* `/url/:id`
* `/url/:id/examples`
* `/url/:id/examples/:exampleNumber`

And this handle all cases:
* `/url/:id`
* `/url/:id/examples`
* `/url/:id/examples/:exampleNumber`
* `/url/:id/`
* `/url/:id/examples/`
* `/url/:id/examples/:exampleNumber/`

**Comment by rjourde** [comment]
Yes. It will just have to be documented.

**Comment by santiaago** [comment]
nice, could you edit the description of this issue #7 with everithing that we just discussed?

**Comment by rjourde** [comment]
Done.

**Comment by santiaago** [comment]
sweet thx :+1:

**Comment by santiaago** [comment]
tests look good, don't forget to update the docs :+1:

**Comment by santiaago** [comment]
I don't know how to extract the **:id** value when I am inside a handler for example inside `userHanlder`?:


~~~~ go
func main() {
	r := new(route.Router)
	r.Handle("/", http.FileServer(http.Dir("/static_files")))
	r.HandleFunc("/users/:id/", userHandler)
	r.AddStaticResource("static/images")
	http.ListenAndServe(":8080", r)
}

func userHandler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Welcome to user handler!")
        // how do I get the :id value here?
}

Also, there is no **test** that extract the value of a `:id`variable inside a handler, that is also missing.

**Comment by rjourde** [comment]
You did not check the latest commit ?
Le dim. 18 janv. 2015 à 02:11, santiaago <notifications@github.com> a
écrit :

**Comment by santiaago** [comment]
Yes I did.

**Comment by rjourde** [comment]
The doc is not yet up to date. And I just figured out that using a simple global map to store URL params is very stupid. At least it should be map with key = request and value = map of string.

**Comment by santiaago** [comment]
sure, I just don't know how to extract a `:id` variable when I am inside a handle, show me how you do that :)

**Comment by rjourde** [comment]
`route.RouterContext.Params["id"]`

**Comment by santiaago** [comment]
looks good, I prefer `route.Context` to `route.RouterContext` what do you thing?

**Comment by rjourde** [comment]
pull request accepted. So close the issue.
